### ISSUE TITLE
Add support to assign parent_id

### ISSUE THREAD

**Issue by Papipo** [saks/mongoid_acts_as_tree#1]
Hi,

I would like to be able to assign a parent_id, since that's how usually things are handled in forms.
right now the gem does not handle changing path and depth fields when you assign the parent_id directly.

Thanks.

**Comment by saks** [comment]
fixed in version 0.1.4

**Comment by Papipo** [comment]
Oh man, that has been quick. Thanks a lot!

**Comment by saks** [comment]
This fix was too quick. Please update gem to version 0.1.5. Sorry for that.

**Comment by Papipo** [comment]
Mmm, you're right, it looks better now. Thanks a lot

**Comment by Papipo** [comment]
How would you handle blank parent_id? If a user does not select a parent in a form, the model with get a parent_id = '', thus raisin a "Document not found for class Thingy with id(s)" exception
