### ISSUE TITLE
Rails 3.1 DEPRECATION WARNING: class_inheritable_attribute

### ISSUE THREAD

**Issue by timoschilling** [saks/mongoid_acts_as_tree#10]
Under Rails 3.1 class_inheritable_attribute is  deprecated

```
DEPRECATION WARNING: class_inheritable_attribute is deprecated, please use class_attribute method instead. Notice their behavior are slightly different, so refer to class_attribute documentation first. (called from <class:Category> at /Users/xxxx/Sites/rails/xxxx/app/models/category.rb:14)
```

**Comment by saks** [comment]
Thanks a lot. It looks like there is no warnings anymore.

**Comment by timoschilling** [comment]
please can you make a new gem version! THX

**Comment by tobidelius** [comment]
When's the new gem version coming? Thx for a great job btw!

**Comment by fabrikagency** [comment]
+1 for a new gem version release. class_inheritable_attribute was removed in Rails 3.2 and the current gem version breaks the app.

**Comment by saks** [comment]
fixed
