### ISSUE TITLE
moving nodes

### ISSUE THREAD

**Issue by kayoubi** [saks/mongoid_acts_as_tree#7]
moving nodes works fine if the moved node has no children (by setting the parent_id) , it doesn't work though for moving nodes with children.

from console
a = Node.find(:first, :conditions => {"name" => "test"})
a.parent_id = "xxxx"
a.save!

NoMethodError: undefined method `_id' for "test":String
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid_acts_as_tree-7fce729/lib/mongoid_acts_as_tree.rb:84:in`fix_position'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid_acts_as_tree-7fce729/lib/mongoid_acts_as_tree.rb:175:in `move_children'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid_acts_as_tree-7fce729/lib/mongoid_acts_as_tree.rb:174:in`each'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid_acts_as_tree-7fce729/lib/mongoid_acts_as_tree.rb:174:in `move_children'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:425:in`_run_save_callbacks'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:93:in `send'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.0.0/lib/active_support/callbacks.rb:93:in`run_callbacks'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid-1a06b10/lib/mongoid/persistence/update.rb:43:in `persist'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid-1a06b10/lib/mongoid/persistence.rb:79:in`update'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid-1a06b10/lib/mongoid/persistence.rb:125:in `upsert'
    from /Library/Ruby/Gems/1.8/bundler/gems/mongoid-1a06b10/lib/mongoid/persistence.rb:70:in`save!'
    from (irb):14

**Comment by saks** [comment]
try out [this](https://gist.github.com/741321).

This script works for me:
<pre><code>
$ rvm 1.8.7
$ ruby ./gist1.rb
Loaded suite ./gist1
Started
.
Finished in 0.017401 seconds.

1 tests, 5 assertions, 0 failures, 0 errors
$ rvm 1.9.2
$ ruby ./gist1.rb
Loaded suite ./gist1
Started
.
Finished in 0.015234 seconds.

1 tests, 5 assertions, 0 failures, 0 errors, 0 skips

Test run options: --seed 63411
</pre></code>

Could you provide some more info about issue?

**Comment by kayoubi** [comment]
sorry, my mistake! my model has a "parent" method which is preventing the same method in your class from being called and causing the error.

**Comment by saks** [comment]
Spunk up, there's nothing to worry about!
